version = 1

exclude_patterns = [
    "next.config.js",
    "tsconfig.json"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  dialect = "typescript"
  plugins = ["react"]
  environment = ["nodejs"]
  style_guide = "airbnb"

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true
